version: 1
disable_existing_loggers: False
formatters:
    json:
        (): core.logger.JsonFormatter
        ensure_ascii: False
        fmt:
            {
                "name": "name",
                "level": "levelname",
#                "trace_id": "trace_id",
                "message": "message",
                "filename": "filename",
                "funcName": "funcName",
                "line_number": "lineno",
                "time": "asctime",
                "traceback": "traceback",
            }
filters:
    healthz:
        (): core.logger.EndpointLogFilter
        path: /healthz
handlers:
    infohandler:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        filters:
            - healthz
        stream: ext://sys.stdout
root:
    handlers: [infohandler]
    level: INFO

