"""
new

Revision ID: 134423acdb34
Revises: 764146ad35f3
Create Date: 2024-10-13 21:30:27.266717

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "134423acdb34"
down_revision: Union[str, None] = "764146ad35f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("position", sa.Column("strategy_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "position", "strategy", ["strategy_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "position", type_="foreignkey")
    op.drop_column("position", "strategy_id")
    op.drop_table("strategy")
    # ### end Alembic commands ###
